### ISSUE TITLE
VDD_SENSOR

### ISSUE THREAD

**Issue by MZhiltsov** [ardntechnology/Hardware#8]
Изменить схему подключения выводов «VDD_3V3_SENSORS» и «VDD_3V3_SENSORS_EN». Заменить транзистор типа MMBT3906LT1SMD (Q201) на резистор сопротивлением 220R, удалив резистор R202 (10R). Вывод «VDD_3V3_SENSORS_EN» подключить на массу через резистор сопротивлением 1М.

**Comment by Viktor-Matitsin** [comment]
Схема изменена: «VDD_3V3_SENSORS» подключен через резистор R621(220R) на массу. Удален транзистор MMBT3906LT1SMD (Q201), удален резистор R202 (10R). Вывод «VDD_3V3_SENSORS_EN» подключен на массу через резистор R103 (1М).
